spring.application.name=sb-ecom
project.image.path=images/
spring.app.jwtSecret=mySecretKey123912738guuihuhiugiyfyuigiukuihu
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookie = springBootEcom


#STATUS OF THE DATABASE:

#only update:
#spring.jpa.hibernate.ddl-auto=update

#delete every time the application runs:
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#RELATED TO DEPLOYMENT IN AWS:
#NEW:
server.port=5000
spring.datasource.url = jdbc:mysql://database-1.cazs2m8ou97a.us-east-1.rds.amazonaws.com/3306

#OLD:
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=lior


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test