name: CI Lite - Playwright on PROD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright (npm package is already in devDependencies)
        working-directory: frontend
        run: npx playwright --version

      - name: Install browsers + OS deps (Ubuntu)
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests against PROD
        working-directory: frontend
        env:
          CI: "true"
          E2E_BASE_URL: "http://54.221.32.104"
        run: npx playwright test -c e2e/playwright.config.js --workers=1

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore
